# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'fair_cg', github: 'rtweeks/fair-cg.git', branch: 'master'
gem 'pry', group: :development
